### ISSUE TITLE
Tests Failing - starting with ember-beta

### ISSUE THREAD

**Issue by pete-the-pete** [emberjs/ember-collection#61]
Running 'npm test' locally fails starting with ember-beta. After running many tests, the first failure is below, with many tests failing in the same way afterwards.
```
ok 33 Chrome 45.0 - JSHint - .: test-helper.js should pass jshint
not ok 34 Chrome 45.0 - manipulate content: replacing the list content
    ---
        actual: >
            null
        message: >
            Died on test #1     at Object.test (http://localhost:7357/assets/test-support.js:2014:11)
                at http://localhost:7357/assets/dummy.js:3688:15
                at mod.state (http://localhost:7357/assets/vendor.js:150:29)
                at tryFinally (http://localhost:7357/assets/vendor.js:30:14)
                at requireModule (http://localhost:7357/assets/vendor.js:148:5)
                at Object.TestLoader.require (http://localhost:7357/assets/test-loader.js:29:9)
                at Object.TestLoader.loadModules (http://localhost:7357/assets/test-loader.js:21:18): this.init is not a function
        Log: |
    ...
```

**Comment by lukemelia** [comment]
Fixed!
